#[cfg(feature = "desktop")]
pub mod album;
#[cfg(feature = "desktop")]
pub mod analysis;
pub mod artwork;
#[cfg(feature = "desktop")]
pub mod audio;
pub mod backup;
pub mod beatport;
pub mod cloud_sync;
#[cfg(feature = "desktop")]
pub mod device;
#[cfg(feature = "desktop")]
pub mod device_sync;
#[cfg(feature = "desktop")]
pub mod diagnostics;
pub mod discovery;
#[cfg(feature = "desktop")]
pub mod duplicate;
#[cfg(feature = "desktop")]
pub mod export;
pub mod follow;
#[cfg(feature = "desktop")]
pub mod hash;
#[cfg(feature = "desktop")]
pub mod library;
#[cfg(feature = "desktop")]
pub mod media_controls;
pub mod playlist;
pub mod player;
pub mod settings;
pub mod smart_rules;
#[cfg(feature = "desktop")]
pub mod standalone;
pub mod stats;
pub mod tag;

#[cfg(feature = "desktop")]
pub use album::AlbumService;
#[cfg(feature = "desktop")]
pub use analysis::AnalysisService;

pub use artwork::ArtworkService;
#[cfg(feature = "desktop")]
pub use audio::AudioService;
pub use backup::BackupService;
pub use beatport::*;
#[cfg(feature = "desktop")]
pub use device::DeviceService;
#[cfg(feature = "desktop")]
pub use device_sync::SyncService;
#[cfg(feature = "desktop")]
pub use diagnostics::DiagnosticsService;
pub use discovery::DiscoveryService;
#[cfg(feature = "desktop")]
pub use duplicate::DuplicateService;
#[cfg(feature = "desktop")]
pub use export::ExportService;
pub use follow::FollowService;
#[cfg(feature = "desktop")]
pub use library::LibraryService;
#[cfg(feature = "desktop")]
pub use media_controls::MediaControlsService;
pub use player::PlayerTrackerService;
pub use playlist::PlaylistService;
pub use settings::SettingsService;
#[cfg(feature = "desktop")]
pub use standalone::StandaloneService;
pub use stats::*;
pub use tag::TagService;

